# Generated by Django 5.2.1 on 2025-06-03 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_bodega_alter_historialprecio_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('disponible', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_serie', to='inventario.producto')),
            ],
        ),
    ]
